show_for_members:
  type: bool
  default: true
  description:
    en: 'Display the banner for users logged into the forum'
show_for_anon:
  type: bool
  default: true
  description:
    en: 'Display the banner for anonymous users'
display_on_mobile:
  type: bool
  default: true
  description:
    en: 'Display the banner on mobile devices'
display_on_desktop:
  type: bool
  default: true
  description:
    en: 'Display the banner on desktop computers'
display_on_homepage:
  type: bool
  default: true
  description:
    en: 'Display the banner on the homepage'
url_must_contain:
  type: list
  list_type: simple
  default: /latest|/categories|/new|/unread|/top*|/tag/*|/tags/*|/c/*|/t/*
  description:
    en: 'Enter paths that should display the banner. Add <code>*</code> to the end of the path as a wildcard'
dismissible:
  type: bool
  default: false
  description:
    en: 'Allow the banner to be closed by users'
collapsible:
  type: bool
  default: true
  description:
    en: 'Allow the banner to be expanded and collapsed by users'
default_collapsed_state:
  type: enum
  default: expanded
  choices:
    - expanded
    - collapsed
  description:
    en: 'Default collapsed state when collapsible setting is enabled'
cookie_lifespan:
  type: enum
  default: month
  choices:
    - minute
    - day
    - week
    - month
    - year
  description:
    en: 'The lifespan of the cookie used to remember if the banner has been closed, expanded, or collapsed.
         If set to "none", NO cookies will be used with this component, and any previously created cookies
         related to the banner will be deleted the next time a user performs a full page load. The values are
         measured as a single unit, so setting "year" will be one year, "week" will be one week, etc.'
cookie_name:
  type: string
  default: "top-banner-xr"
  description:
    en: 'When important changes are made to the banner, you must change the cookie name to ensure all your users see the changes.'
full_width_banner:
  type: bool
  default: true
  description:
    en: 'Display the banner at full browser width'
swap_default_positioning:
  type: bool
  default: false
  description:
    en: 'If there is another banner-related component active, use this to swap its position with the Versatile Banner'
banner_background_image:
  type: string
  default: "https://elokapina.fi/assets/img/xr-shock-face.png"
  description:
    en: 'The source url for your background image. Tip: You can upload an image to your main theme and use the url from that,
         but make sure that you do not use "Uploads" section of this component. Any uploads added to this component will be
         deleted whenever it is updated.'
background_color:
  type: string
  default: "#fff"
  description:
    en: 'Used in place of a background image'
primary_text_color:
  type: string
  default: "#222"
  description:
    en: 'The main text color of the banner'
secondary_text_color:
  type: string
  default: "#666"
  description:
    en: 'The text color of the icon and text headings, and the button background color.'
link_text_color:
  type: string
  default: "#646464"
  description:
    en: 'The text color links within the banner.
        <br><br><br>
        <h2>Banner Content Customization</h2>
        Customize the content of the banner with HTML. If you need to style your custom content
        with CSS, create a separate theme component. Leave the content blank to exclude a column.
        While a fourth column is provided, it will likely result in too much content for the
        available space. Be sure you are happy with your configuration across different brower widths.'
main_heading_content:
  type: string
  textarea: true
  default: |
            <h1 class="x-title">
              Tervetuloa Elokapinan baseen!
            </h1>
            <h2 class="description" style="font-family: 'Montserrat'; font-size: 1.2rem;"> Voit tarkastella Wiki-postauksia, Uutiskirjeitä ja Ryhmät-sivua ilman rekisteröitymistä. Jotta pääset seuraamaan ja osallistumaan keskusteluihin, tarvitset omat tunnukset. Saat kapinatunnukset osallistumalla Elokapinan työ-, paikallis- tai teemaryhmien toimintaan. Kapinatunnukset saat myös osallistumalla koulutuksiin.</h2>
first_column_content:
  type: string
  textarea: true
  default: |
            <h2>Elokapinan Base</h2>
            <p>
              Base on keskustelu- ja päätöksentekoalusta Suomessa toimiville elokapinallisille. Sen tarkoituksena on täydentää nopeaa chättimuotoista keskustelua ja mahdollistaa laajempien keskusteluiden käyminen yhdessä. Se tarjoaa joukon <a href="https://docs.elokapina.fi/oppaat/viestintaealustat/base-foorumialusta#muutamia-basen-taerkeimmistae-ominaisuuksista" style="color: blue !important;" target="_blank" rel="noopener"> ominaisuuksia</a>, jotka auttavat tiedon löytämisessä ja summaamisessa.
            </p>

            <div class="button-list">
            <ul>
                <li><a href="/faq" class="btn btn-icon-text">Yhteiset pelisäännöt</a></li>
            </ul>
            </div>
second_column_content:
  type: string
  textarea: true
  default: |
            <h2>Miten pääset alkuun?</h2>
            <p>
              Olitpa uusi elokapinassa tai tarvitset päivitystä tietoihisi, esittelymateriaalimme auttaa sinut eteenpäin.
            </p>
            <h4>Ensiaskeleet</h4>
            <div class="button-list">
              <ul>
                <li><a href="/t/ensimmaiset-askeleet-sivu-1-tervetuloa-elokapinan-paamajaan/7" class="btn btn-icon-text">1. Ensiaskeleet Elokapinan Baseen</a></li>
                <li><a href="/g?filter=pr-"  class="btn btn-icon-text">2. Liity paikallisryhmääsi basessa</a></li>
                <li><a href="/g?filter=ktr-" class="btn btn-icon-text">3. Selaa ja pyydä liittyä työryhmään </a></li>
            </div>
            <p>Kysymyksiä Elokapinaan tai foorumin käyttöön liittyen? Kirjoita avoimia kysymyksiä alueelle <a class="hashtag" href="/c/tuki/">#tuki</a>, tai ota yhteyttä foorumin moderaattoreihin <a class="mention-group notify" href="/g/henkilokunta">@henkilokunta</a>.</p>
third_column_content:
  type: string
  textarea: true
  default: |
            <h2>Lisälukemista</h2>
            <p>
              Olemme koonneet tähän materiaaleja, jotka auttavat tiedon löytämisessä.
            </p>
            <h4>Hyödyllisiä materiaaleja</h4>
            <div class="button-list">
              <ul>
                <li><a href="/t/tutorial-elokapinan-tyoryhmat-organisaatio-sivu-1/323" class="btn btn-icon-text">Elokapinan organismi</a></li>

            <li><a href="https://docs.elokapina.fi/" class="btn btn-icon-text"  target="_blank" rel="noopener">Palvelujen dokumentaatio</a></li>

            <li><a href="/t/wiki-international-xr-document-index/227" class="btn btn-icon-text">Kansainvälinen dokumentti-indeksi</a></li>

              </ul>
            </div>
fourth_column_content:
  type: string
  textarea: true
  default: ''
  description:
    en: ''
first_column_size:
  type: string
  default: 'auto'
second_column_size:
  type: string
  default: 'auto'
third_column_size:
  type: string
  default: 'auto'
fourth_column_size:
  type: string
  default: ''
  description:
    en: ''
first_column_icon:
  type: string
  default: 'https://base.organise.earth/uploads/default/original/1X/99a6af493fc77c7e31bb171379ab211dc099c878.png'
second_column_icon:
  type: string
  default: 'far-question-circle'
third_column_icon:
  type: string
  default: 'https://base.organise.earth/uploads/default/original/1X/4486a773d690716bdea691639b2f6968bf8b4b04.png'
fourth_column_icon:
  type: string
  default: ''
